name: CI

on:
  push:
    branches: [ main ]


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build images
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d api db

      - name: Wait for services
        run: sleep 15

      - name: Test API Endpoint
        run: |
          docker-compose exec -T api curl -f http://localhost/get_tickets.php
          docker-compose ps

      - name: Test_Unit
        run: |
          docker-compose exec -T api curl -f http://localhost/tests/test_unit.php

      - name: UI test
        run: docker-compose exec -T api bash /var/www/html/tests/test_ui.sh

      - name: Tear down
        if: always()
        run: docker-compose down